In [25]:
import numpy as np
import pandas as pd

In [71]:
features = pd.read_csv('Data/data.csv')
labels = pd.read_csv('Data/target.csv')
feature_names = pd.read_csv('Data/feature_names.csv')
label_names = ['Boxing','Not Boxing']

labels = np.ravel(labels.as_matrix(columns=None))
feature_names = np.ravel(feature_names.as_matrix(columns=None))
features = features.as_matrix(columns=None)
type(features)

numpy.ndarray

In [72]:
print(labels.shape)
print(feature_names.shape)
labels

(196639,)
(48,)


array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [73]:
# Look at our data
print(label_names)
print(labels[0])
print(feature_names[0])
print(features[0])

['Boxing', 'Not Boxing']
1
R_Hip_x
[ 4.0346e+00 -1.4868e+02 -1.9560e+02 -9.7643e+01  1.3078e+02  1.4187e+02
  1.5220e+02  3.1806e+01  4.3412e+01 -5.7568e+00  3.9162e+01  1.6918e+02
  1.8589e+02  4.1456e+01 -8.4717e+01 -2.8129e+02 -2.7494e+02  2.3197e+01
  8.8731e+01 -2.1414e+01  1.0475e+02 -4.2338e+01 -1.3711e+02  1.1952e+01
  7.8310e+01  7.9528e+01 -4.9591e-01  5.7685e+01  7.7683e+00 -1.7935e+02
 -2.6214e+02  1.5557e+02  1.2776e+02 -5.6859e+01 -1.5105e+02 -2.4011e+02
 -6.7552e+02 -9.8912e+02 -2.1718e+02 -6.0028e+02 -9.6434e+02  1.3296e+02
  4.1340e+02  5.4514e+02  6.0310e+02  3.8813e+02  1.0722e+02  3.1633e+02
  3.9024e+02  1.3864e+02  3.2561e+02]


In [74]:
from sklearn.model_selection import train_test_split

# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                          labels,
                                                          test_size=0.15,
                                                          random_state=42)

In [75]:
test_labels

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [76]:
from sklearn.naive_bayes import GaussianNB

# Initialize our classifier
gnb = GaussianNB()

# Train our classifier
model = gnb.fit(train, train_labels)

In [77]:
# Make predictions
preds = gnb.predict(test)
print(preds)

[0 0 1 ... 1 0 0]


In [78]:
from sklearn.metrics import accuracy_score

# Evaluate accuracy
print(accuracy_score(test_labels, preds))

0.6978234336859235
